spring:
  profiles:
    active: dev

# 腾讯云COS
cos:
  secretId: AKIDiJrpcGV4GG4j7KwJo8HGE4iARmxxCRlu
  secretKey: 62veBXjeaXM6f3FQjrobFi075oMiv0ta
  bucketName: iceblue-1257085658
  domain: https://iceblue-1257085658.cos.ap-guangzhou.myqcloud.com/

mongo:
  mongoDbName: course_learning_management
  host: 139.224.8.162
  port: 27017
  username: admin
  password: 123456789

# 微信小程序配置
wechat:
  appId: AKIDiJrpcGV4GG4j7KwJo8HGE4iARmxxCRlu
  secret: aaaaabbbb